name: CI

on: [push, pull_request]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: cmake
      run: cmake .
    - name: make
      run: make
    - name: test
      run: ctest --output-on-failure

  macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: cmake
      run: cmake .
    - name: make
      run: make
    - name: test
      run: ctest --output-on-failure

  Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: cmake
      run: cmake -G "Visual Studio 16 2019" .
    - name: make
      run: cmake --build .
    - name: test
      # Run all non-bash tests on Windows
      run: ctest -E bash -V
